/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Lab;

import Business.EcoSystem;
import Business.Enterprise.BloodBankEnterprise;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.BloodCollectionStationOrganization;
import Business.Organization.DonorOrganisation;
import Business.Organization.LabOrganization;
import Business.Organization.MedicalOrganisation;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Bussiness.WorkQueue.DonorRequest;
import Bussiness.WorkQueue.MedicineRequest;
import Bussiness.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author namratha
 */
public class testResultsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form testResultsJPanel
     */
     private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private DonorRequest request;
    private Enterprise enterprise;

    public testResultsJPanel(JPanel userProcessContainer, UserAccount account, DonorRequest request,
            Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.request = (DonorRequest) request;
        this.enterprise = enterprise;
        this.business=business; 
        initComponents();
        populateGroupComboBox();
    }
     public void populateGroupComboBox()
      {
         bloodGroupDropDown.removeAllItems();
         bloodGroupDropDown.addItem("A+");
         bloodGroupDropDown.addItem("A-");
         bloodGroupDropDown.addItem("B+");
         bloodGroupDropDown.addItem("B-");
         bloodGroupDropDown.addItem("O+");
         bloodGroupDropDown.addItem("O-");
         bloodGroupDropDown.addItem("AB+");
         bloodGroupDropDown.addItem("AB-");
                                 
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BPTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tempTxtField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        HRTxtField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        platlatesTxtField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        healthyYesBtn = new javax.swing.JRadioButton();
        HealthyNoBtn = new javax.swing.JRadioButton();
        AntibioticYes = new javax.swing.JRadioButton();
        AntibioticNo = new javax.swing.JRadioButton();
        VaccineYes = new javax.swing.JRadioButton();
        vaccineNo = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        InfectionYes = new javax.swing.JRadioButton();
        InfectionNo = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        AspirinYes = new javax.swing.JRadioButton();
        AspirinNo = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        bloodYes = new javax.swing.JRadioButton();
        BloodNo = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        MedicineTxtField = new javax.swing.JTextField();
        PrescribeMedicineBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        MedicineListTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        bloodGroupDropDown = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(254, 254, 254));

        jLabel1.setText("BP");

        BPTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPTxtFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Temperature");

        tempTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempTxtFieldActionPerformed(evt);
            }
        });

        jLabel3.setText("Heart Rate");

        HRTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HRTxtFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Platlates");

        platlatesTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                platlatesTxtFieldActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel5.setText("Are You");

        healthyYesBtn.setText("Yes");

        HealthyNoBtn.setText("No");

        AntibioticYes.setText("Yes");

        AntibioticNo.setText("No");

        VaccineYes.setText("Yes");
        VaccineYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VaccineYesActionPerformed(evt);
            }
        });

        vaccineNo.setText("No");

        jLabel6.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel6.setText("In the past 48 hours");

        jLabel7.setText("Have you taken aspirin or anything that has aspirin in it?");

        InfectionYes.setText("Yes");
        InfectionYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfectionYesActionPerformed(evt);
            }
        });

        InfectionNo.setText("No");
        InfectionNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfectionNoActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel8.setText("In the past 8 weeks, have you");

        jLabel9.setText("Donated blood, platelets or plasma?");

        AspirinYes.setText("Yes");
        AspirinYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AspirinYesActionPerformed(evt);
            }
        });

        AspirinNo.setText("No");

        jLabel10.setText("Had any vaccinations or other shots?");

        bloodYes.setText("Yes");
        bloodYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodYesActionPerformed(evt);
            }
        });

        BloodNo.setText("No");

        jLabel11.setText("Feeling healthy and well today?");

        jLabel12.setText("Currently taking any antibiotic?");

        jLabel13.setText("Currently taking any other medication for an infection?");

        submitBtn.setBackground(new java.awt.Color(255, 153, 102));
        submitBtn.setForeground(new java.awt.Color(254, 254, 254));
        submitBtn.setText("Submit Result");
        submitBtn.setPreferredSize(new java.awt.Dimension(197, 41));
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });

        jLabel14.setText("Medicine");

        MedicineTxtField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicineTxtFieldActionPerformed(evt);
            }
        });

        PrescribeMedicineBtn.setBackground(new java.awt.Color(255, 153, 102));
        PrescribeMedicineBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        PrescribeMedicineBtn.setForeground(new java.awt.Color(254, 254, 254));
        PrescribeMedicineBtn.setText("Prescribe Medicines");
        PrescribeMedicineBtn.setPreferredSize(new java.awt.Dimension(197, 41));
        PrescribeMedicineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrescribeMedicineBtnActionPerformed(evt);
            }
        });

        MedicineListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Donor", "Medicine"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(MedicineListTable);

        backBtn.setBackground(new java.awt.Color(255, 153, 102));
        backBtn.setFont(new java.awt.Font("Ubuntu", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(254, 254, 254));
        backBtn.setText("<<Back");
        backBtn.setPreferredSize(new java.awt.Dimension(197, 41));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Enter Test Reports");

        jLabel15.setText("Blood Group");

        bloodGroupDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel15))
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(HRTxtField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(platlatesTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(bloodGroupDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(40, 40, 40)
                                .addComponent(tempTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(BPTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PrescribeMedicineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(205, 205, 205))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(38, 38, 38)
                                .addComponent(MedicineTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(179, 179, 179)
                                .addComponent(healthyYesBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(HealthyNoBtn))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AntibioticYes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AntibioticNo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(InfectionYes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(InfectionNo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(AspirinYes)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(AspirinNo))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(VaccineYes)
                                            .addComponent(bloodYes))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(BloodNo)
                                            .addComponent(vaccineNo))))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(tempTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(HRTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(platlatesTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BPTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bloodGroupDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(healthyYesBtn)
                            .addComponent(HealthyNoBtn))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(AntibioticYes)
                            .addComponent(AntibioticNo))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(InfectionYes)
                            .addComponent(InfectionNo))
                        .addGap(27, 27, 27)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(AspirinYes)
                                .addComponent(AspirinNo)))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(bloodYes)
                                        .addComponent(BloodNo)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(VaccineYes)
                                .addComponent(vaccineNo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(submitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(107, 107, 107))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(MedicineTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addComponent(PrescribeMedicineBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BPTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BPTxtFieldActionPerformed

    private void tempTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempTxtFieldActionPerformed

    private void HRTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HRTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HRTxtFieldActionPerformed

    private void platlatesTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_platlatesTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_platlatesTxtFieldActionPerformed

    private void VaccineYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VaccineYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VaccineYesActionPerformed

    private void AspirinYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AspirinYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AspirinYesActionPerformed

    private void bloodYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodYesActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
       
       
        
        
        Boolean sel=true;
        Boolean error=false;
        try{
         int Bp=Integer.parseInt(BPTxtField.getText());
        int Hr=Integer.parseInt(HRTxtField.getText());
        int temp=Integer.parseInt(tempTxtField.getText());
        int pulse=Integer.parseInt(platlatesTxtField.getText());
        if (healthyYesBtn.isSelected() && AntibioticNo.isSelected() && InfectionNo.isSelected() && AspirinNo.isSelected() && 
                BloodNo.isSelected() && vaccineNo.isSelected() && (pulse>150000 && pulse<600000 ) &&(temp<100 && temp>96)
                && (Hr<80 &&Hr>60) && (Bp<140 && Bp>110)
                ) {
               sel=true;   
         }
        else{
        
          sel=false;
        }
        }
        catch (Exception e3){
              sel=false;
              error=true;
                JOptionPane.showMessageDialog(null, "Please input the details in proper format", "Warning", JOptionPane.WARNING_MESSAGE);
            
                
         }
//        if (HealthyNoBtn.isSelected()) {
//               sel=false;   
//         }
//        if(AntibioticNo.isSelected()){
//               sel=true;
//        }
//        if(AntibioticYes.isSelected()){
//                sel=true;
//        }
//        if(InfectionNo.isSelected()){
//                sel=false;
//        }
//        if(InfectionYes.isSelected()){
//                sel=true;
//        }
//        if(AspirinNo.isSelected()){
//            sel=false;
//        }
//        if(AspirinYes.isSelected()){
//           sel=true;
//        }
//        if(BloodNo.isSelected()){
//            sel=false;
//        }
//        if(bloodYes.isSelected()){
//            sel=true;
//        }
//        if(VaccineYes.isSelected()){
//            sel=true;
//        }
//        if(vaccineNo.isSelected()){
//              sel=false;
//        }
          
        if(sel==false && error == false){
          
            request.setStatus("Not approved");
            JOptionPane.showMessageDialog(null, "You are not eligible to donate blood", "Information", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        else if(sel==true && error== false){
             request.setStatus("Completed");
             JOptionPane.showMessageDialog(null, "Test Successful", "Information", JOptionPane.INFORMATION_MESSAGE);
             Organization org = null;
                for (Network network : business.getNetworkList()) {
                    for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                        if (enterprise instanceof BloodBankEnterprise) {
                            for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                                if (organization instanceof BloodCollectionStationOrganization) {
                                    org = organization;
                                    break;
                                }
                            }
                        }

                    }
                }

                if (org != null) {
                    System.out.println("userinterface.Farmer.RequestDoctorTreatmentWorkAreaJPanel.requestTestJButtonActionPerformed()");
                    request.setBlood(bloodGroupDropDown.getSelectedItem().toString());
                    org.getWorkQueue().getWorkRequestList().add(request);
                    userAccount.getWorkQueue().getWorkRequestList().add(request);
                    
             
        }
        }
             
    }//GEN-LAST:event_submitBtnActionPerformed
public void populateRequestTable() {
        DefaultTableModel model = (DefaultTableModel) MedicineListTable.getModel();

        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()) {
            if (request.getClass() != null) {
                String x = request.getClass().toString();
                //Business.WorkQueue.CarrierWorkRequest
                //String x = request.getReceiver().getRole().toString();
                if(x.contains("MedicineRequest")){
                    MedicineRequest medicineWorkRequest = (MedicineRequest) request;
                    Object[] row = new Object[2];
                    row[1] = medicineWorkRequest.getMedicine();
                    row[0] = medicineWorkRequest;

                    model.addRow(row);
                }
              
            }
        }
    }
    private void PrescribeMedicineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrescribeMedicineBtnActionPerformed
        // TODO add your handling code here:
       
        String medicineName = MedicineTxtField.getText();
       
       
        
        MedicineRequest  medicineRequest=new MedicineRequest();
     
        medicineRequest.setSender(request.getSender());
        medicineRequest.setMedicine(medicineName);
        System.out.println(medicineRequest);
       

        Organization org = null;
        for (Network network : business.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                if (enterprise instanceof BloodBankEnterprise) {
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof DonorOrganisation) {
                            org = organization;
                            //                            System.out.println("orgname" + organization.getName());
                            org.getWorkQueue().getWorkRequestList().add(medicineRequest);
                            break;
                        }
                    }
                }

            }
        }

        if (org != null) {

            userAccount.getWorkQueue().getWorkRequestList().add(medicineRequest);
            JOptionPane.showMessageDialog(null, "Requested medicines successfully", "Information", JOptionPane.INFORMATION_MESSAGE);
            populateRequestTable();

        }
    }//GEN-LAST:event_PrescribeMedicineBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        LabJPanel dwjp = (LabJPanel) component;
        dwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void InfectionYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfectionYesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfectionYesActionPerformed

    private void InfectionNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfectionNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InfectionNoActionPerformed

    private void MedicineTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicineTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicineTxtFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton AntibioticNo;
    private javax.swing.JRadioButton AntibioticYes;
    private javax.swing.JRadioButton AspirinNo;
    private javax.swing.JRadioButton AspirinYes;
    private javax.swing.JTextField BPTxtField;
    private javax.swing.JRadioButton BloodNo;
    private javax.swing.JTextField HRTxtField;
    private javax.swing.JRadioButton HealthyNoBtn;
    private javax.swing.JRadioButton InfectionNo;
    private javax.swing.JRadioButton InfectionYes;
    private javax.swing.JTable MedicineListTable;
    private javax.swing.JTextField MedicineTxtField;
    private javax.swing.JButton PrescribeMedicineBtn;
    private javax.swing.JRadioButton VaccineYes;
    private javax.swing.JButton backBtn;
    private javax.swing.JComboBox<String> bloodGroupDropDown;
    private javax.swing.JRadioButton bloodYes;
    private javax.swing.JRadioButton healthyYesBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField platlatesTxtField;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField tempTxtField;
    private javax.swing.JRadioButton vaccineNo;
    // End of variables declaration//GEN-END:variables
}
