/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Donor;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DonorOrganisation;
import Business.Organization.EventsOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Bussiness.WorkQueue.DonorRequest;
import Bussiness.WorkQueue.EventRequest;
import Bussiness.WorkQueue.MedicineRequest;
import Bussiness.WorkQueue.WorkRequest;
import UserInterface.CreateEvents.ViewEventJPanel;
import UserInterface.Doctor.DoctorWQJPanel;
import UserInterface.Lab.LabJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author dell_owner
 */
public class DonorViewEventsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonorViewEvents
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Organization organization;
    private DonorOrganisation donorOrganisation;
    private Enterprise enterprise;
    private EventsOrganization eventsOrganization;
    
    public DonorViewEventsJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem business, Organization organization) {
        initComponents();
        this.donorOrganisation = (DonorOrganisation) organization;
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.enterprise = enterprise;
        populateTable();
    }
    
    class LabelRenderer implements TableCellRenderer{
        public Component getTableCellRendererComponent(JTable table, Object value,  boolean isSelected, boolean hasFocus, int row, int column){
            TableColumn tc = table.getColumn("Image");
            tc.setMinWidth(100);
            table.setRowHeight(100);
            return (Component) value;
        }
    }
    public void populateTable() {
        System.out.println("hi");
        DefaultTableModel model = (DefaultTableModel) dViewEvents.getModel();
        Object[] newIdentifiers = new Object[]{"Creator", "Title", "Location", "Date", "Time", "Image"};
        model.setColumnIdentifiers(newIdentifiers);
        dViewEvents.getColumn("Image").setCellRenderer(new DonorViewEventsJPanel.LabelRenderer());
        model.setRowCount(0);
        System.out.println(donorOrganisation.getWorkQueue().getWorkRequestList().size());
        for (WorkRequest request : donorOrganisation.getWorkQueue().getWorkRequestList()) {
            System.out.println("Hi");
            if (request.getClass() != null) {
                String x = request.getClass().toString();
                System.out.println("Hi");
                //Business.WorkQueue.CarrierWorkRequest
                //String x = request.getReceiver().getRole().toString();
                
                //Business.WorkQueue.CarrierWorkRequest
                //String x = request.getReceiver().getRole().toString();
                System.out.println(request);
                if(x.contains("Donor")){
                    DonorRequest donorWorkRequest = (DonorRequest) request;
                    if (donorWorkRequest.getIsEventReq() == true) {
                        Object[] row = new Object[6];
                        JLabel imagelabel = new JLabel();
                        System.out.println(donorWorkRequest.getEventtitle());
                        ImageIcon imageIcon = new ImageIcon(donorWorkRequest.getEventimage());
                        Image imageIc = imageIcon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                        imagelabel.setIcon(new ImageIcon(imageIc));
                        row[1] = donorWorkRequest.getEventtitle();
                        row[2] = donorWorkRequest.getEventlocation();
                        donorWorkRequest.setEventreceiver(userAccount);
                        row[0] =donorWorkRequest.getEventsender();
                        row[3]=donorWorkRequest.getEventdate();
                        row[4]=donorWorkRequest.getEventtime();
                        row[5]=imagelabel;
                        model.addRow(row);
                }
                }
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dViewEvents = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        dViewEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dViewEvents.setGridColor(new java.awt.Color(254, 254, 254));
        jScrollPane1.setViewportView(dViewEvents);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("View All Events");

        jButton1.setBackground(new java.awt.Color(255, 153, 102));
        jButton1.setText("<<BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1187, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        DonorJPanel dwjp = (DonorJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dViewEvents;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
