/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Donor;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.DonorOrganisation;
import Business.Organization.EventsOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Bussiness.WorkQueue.DonorRequest;
import Bussiness.WorkQueue.EventRequest;
import Bussiness.WorkQueue.MedicineRequest;
import Bussiness.WorkQueue.WorkRequest;
import UserInterface.CreateEvents.ViewEventJPanel;
import UserInterface.Doctor.DoctorWQJPanel;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Image;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author dell_owner
 */
public class DonorViewEventsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DonorViewEvents
     */
    private JPanel userProcessContainer;
    private EcoSystem business;
    private UserAccount userAccount;
    private Organization organization;
    private DonorOrganisation donorOrganisation;
    private Enterprise enterprise;
    private EventsOrganization eventsOrganization;
    
    public DonorViewEventsJPanel(JPanel userProcessContainer, UserAccount account, Enterprise enterprise, EcoSystem business, Organization organization) {
        initComponents();
        this.donorOrganisation = (DonorOrganisation) organization;
        this.userProcessContainer = userProcessContainer;
        this.userAccount = account;
        this.business = business;
        this.enterprise = enterprise;
        populateTable();
    }
    
    class LabelRenderer implements TableCellRenderer{
        public Component getTableCellRendererComponent(JTable table, Object value,  boolean isSelected, boolean hasFocus, int row, int column){
            TableColumn tc = table.getColumn("Image");
            tc.setMinWidth(100);
            table.setRowHeight(100);
            return (Component) value;
        }
    }
    public void populateTable() {
        System.out.println("hi");
        DefaultTableModel model = (DefaultTableModel) dViewEvents.getModel();
        Object[] newIdentifiers = new Object[]{"Creator", "Title", "Location", "Date", "Time", "Image"};
        model.setColumnIdentifiers(newIdentifiers);
        dViewEvents.getColumn("Image").setCellRenderer(new DonorViewEventsJPanel.LabelRenderer());
        model.setRowCount(0);
        System.out.println(donorOrganisation.getWorkQueue().getWorkRequestList().size());
        for (WorkRequest request : donorOrganisation.getWorkQueue().getWorkRequestList()) {
            System.out.println("Hi");
            if (request.getClass() != null) {
                String x = request.getClass().toString();
                System.out.println("Hi");
                //Business.WorkQueue.CarrierWorkRequest
                //String x = request.getReceiver().getRole().toString();
                
                //Business.WorkQueue.CarrierWorkRequest
                //String x = request.getReceiver().getRole().toString();
                System.out.println(request);
                if(x.contains("Donor")){
                    DonorRequest donorWorkRequest = (DonorRequest) request;
                    if (donorWorkRequest.getIsEventReq() == true) {
                        Object[] row = new Object[6];
                        JLabel imagelabel = new JLabel();
                        System.out.println(donorWorkRequest.getEventtitle());
                        ImageIcon imageIcon = new ImageIcon(donorWorkRequest.getEventimage());
                        Image imageIc = imageIcon.getImage().getScaledInstance(100, 100, Image.SCALE_SMOOTH);
                        imagelabel.setIcon(new ImageIcon(imageIc));
                        row[1] = donorWorkRequest.getEventtitle();
                        row[2] = donorWorkRequest.getEventlocation();
                        donorWorkRequest.setEventreceiver(userAccount);
                        row[0] =donorWorkRequest.getEventsender();
                        row[3]=donorWorkRequest.getEventdate();
                        row[4]=donorWorkRequest.getEventtime();
                        row[5]=imagelabel;
                        model.addRow(row);
                }
                }
                
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dViewEvents = new javax.swing.JTable();
        RegisterBtn = new javax.swing.JButton();

        dViewEvents.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dViewEvents);

        RegisterBtn.setText("Register");
        RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(RegisterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RegisterBtn)
                .addContainerGap(127, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterBtnActionPerformed
        // TODO add your handling code here:
        int selected = dViewEvents.getSelectedRow();

        if (selected >=0) {
             System.out.println("hello nam");
            String title = dViewEvents.getValueAt(selected, 1).toString();
            String location = dViewEvents.getValueAt(selected, 2).toString();

            String date = dViewEvents.getValueAt(selected, 3).toString();
            String time = dViewEvents.getValueAt(selected, 4).toString();
            System.out.println("title"+title+"location"+location+"date"+date);
            System.out.println("hello nam");
            System.out.println();
            ArrayList<String> events = userAccount.getEvents();
            events.add(title);
            userAccount.setEvents(events);
            
            ArrayList<String> locations = userAccount.getEventLocations();
            locations.add(location);
            userAccount.setEvents(events);
            
            ArrayList<String> dates = userAccount.getEventDates();
            dates.add(date);
            userAccount.setEvents(dates);
            
            ArrayList<String> times = userAccount.getEventTimes();
            times.add(time);
            userAccount.setEvents(times);
            System.out.println("events"+userAccount.getEvents()+"location"+userAccount.getEventLocations());
            
        }
        
    }//GEN-LAST:event_RegisterBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton RegisterBtn;
    private javax.swing.JTable dViewEvents;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
